"""Agent 3 — The Debugger (QA Code Reviewer), optimized for live demos.

Takes the Architect's JSON plan plus the Developer's raw page.tsx code and
returns a cleaned, fixed version of the code.

Hybrid fast-check strategy (keeps live-demo latency near zero):
- First runs a structural sanity check (use client directive, balanced
  braces/parens, no markdown fences, plan sections present).
- If `fast_mode=True` (the demo default) OR the code passes the structural
  check, the LLM is skipped entirely and the code is returned in <0.1s.
- The expensive LLM repair pass (fast model + max_tokens cap) only runs
  when `fast_mode=False` AND the structural check finds real problems.

Runs strictly on the NVIDIA API (https://integrate.api.nvidia.com/v1) using
NVIDIA_API_KEY — no Groq or Ollama for this agent.
"""
import json
import os
import re
from typing import Optional, Tuple

from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()

NVIDIA_BASE_URL = "https://integrate.api.nvidia.com/v1"
# Fast instruct model for the rare repair pass. (The nemotron-3-super QA pass
# took 12+ minutes on a full page — far too slow for a live demo, so it is no
# longer the default; override with DEBUGGER_MODEL if wanted.)
DEFAULT_MODEL = os.getenv("DEBUGGER_MODEL", "meta/llama-3.1-nemotron-70b-instruct")
# Cap the repair pass so a runaway generation can't stall the request.
REPAIR_MAX_TOKENS = int(os.getenv("DEBUGGER_MAX_TOKENS", "8000"))

SYSTEM_PROMPT = """You are a Senior QA Code Reviewer Agent for a Next.js + Tailwind CSS
website generation pipeline.

You will receive:
1. A JSON layout plan (site type, niche, theme, color palette, sections,
   features, component requirements) — the source of truth for what the
   page must contain.
2. A raw `page.tsx` React file generated by a Developer Agent that FAILED
   structural validation.

Your job is to repair the code:
- Fix any syntax errors, TypeScript/JSX errors, or unclosed tags.
- Ensure all required React imports are present (useState, useEffect, etc.
  must be imported from "react" if used).
- Ensure the file is a complete, valid Next.js App Router page: a
  "use client" directive at the top and a default-exported component.
- Ensure every section in the plan's "sections" array is implemented, in
  order, using the plan's exact color_palette hex values and theme.
- Styling must be Tailwind utility classes only. No external packages,
  imports, or assets.

Preserve the Developer's overall design, copy, and structure — only fix what
is broken or missing per the plan.

Output ONLY the cleaned, fully fixed raw `page.tsx` code. Do NOT wrap it in
markdown fences (no ```tsx). Do NOT include any explanation, commentary, or
conversational text. Your entire response must start with the first line of
the file ("use client" or the first import) and end with the last line."""


class DebuggerAgent:
    """Validates and fixes Developer page code against the Architect plan."""

    def __init__(self, model: Optional[str] = None, base_url: str = NVIDIA_BASE_URL):
        self.base_url = base_url
        self.model = model or DEFAULT_MODEL
        api_key = os.environ.get("NVIDIA_API_KEY")
        if not api_key:
            raise ValueError(
                "NVIDIA_API_KEY not found in environment variables. "
                "Add it to ai_engine/.env or export it before running."
            )
        self.client = OpenAI(base_url=self.base_url, api_key=api_key)

    @staticmethod
    def structural_check(code: str, plan_json: Optional[dict] = None) -> Tuple[bool, list]:
        """Cheap (<1ms) structural validation of a page.tsx string.

        Returns (passed, problems). Checks: starts with 'use client' or an
        import, no markdown fences, balanced braces/parens/brackets (string
        and comment literals stripped first), and — when a plan is given —
        that every planned section is present in the code.
        """
        problems = []
        if not code or not code.strip():
            return False, ["empty code"]

        text = code.strip()
        if not text.startswith(('"use client"', "'use client'", "import")):
            problems.append("missing 'use client' directive or leading import")
        if "```" in code:
            problems.append("markdown fences present")

        # Strip string literals and comments so their contents don't skew
        # the bracket-balance counts.
        stripped = re.sub(r"//[^\n]*", "", text)          # line comments
        stripped = re.sub(r"/\*.*?\*/", "", stripped, flags=re.DOTALL)  # block comments
        stripped = re.sub(r'"(?:\\.|[^"\\])*"', '""', stripped)
        stripped = re.sub(r"'(?:\\.|[^'\\])*'", "''", stripped)
        stripped = re.sub(r"`(?:\\.|[^`\\])*`", "``", stripped)
        for open_ch, close_ch, name in (("{", "}", "braces"),
                                        ("(", ")", "parens"),
                                        ("[", "]", "brackets")):
            if stripped.count(open_ch) != stripped.count(close_ch):
                problems.append(f"unbalanced {name}: "
                                f"{stripped.count(open_ch)} open vs {stripped.count(close_ch)} close")

        if plan_json:
            flat_code = re.sub(r"[\s-]", "", code.lower())
            for section in plan_json.get("sections", []):
                if re.sub(r"[\s-]", "", section.lower()) not in flat_code:
                    problems.append(f"missing planned section: {section}")

        return len(problems) == 0, problems

    def validate_and_fix_code(self, plan_json: dict, code: str,
                              fast_mode: bool = True) -> str:
        """Hybrid validation/repair.

        fast_mode=True (demo default) or a passing structural check skips the
        LLM entirely and returns the code in <0.1s. The LLM repair pass runs
        only when fast_mode=False AND the structural check fails.
        """
        if not code or not code.strip():
            return code

        passed, problems = self.structural_check(code, plan_json)

        if fast_mode or passed:
            if problems:
                print(f"[DebuggerAgent] fast_mode: skipping LLM repair; structural "
                      f"problems noted: {problems}")
            else:
                print("[DebuggerAgent] structural check passed — skipping LLM repair.")
            return code

        # Slow path: real problems found and thorough mode requested.
        print(f"[DebuggerAgent] structural problems, running LLM repair "
              f"({self.model}, max_tokens={REPAIR_MAX_TOKENS}): {problems}")
        try:
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {
                        "role": "user",
                        "content": (
                            "JSON layout plan:\n\n"
                            + json.dumps(plan_json, indent=2)
                            + "\n\nRaw page.tsx code to validate and fix:\n\n"
                            + code
                        ),
                    },
                ],
                temperature=0.1,
                max_tokens=REPAIR_MAX_TOKENS,
            )
            content = response.choices[0].message.content
            fixed = self._strip_to_code(content)
            # Never return an empty "fix" — keep the original if the model
            # responded with nothing usable.
            return fixed if fixed else code
        except Exception as e:
            print(f"[DebuggerAgent] NVIDIA call failed, keeping original code: {e}")
            return code

    @staticmethod
    def _strip_to_code(content: str) -> str:
        """Defensively strip markdown fences and stray prose. The model is
        told to return raw code only, but wrap-proof anyway."""
        if not content or not content.strip():
            return ""

        text = content.strip()
        text = re.sub(r"^```[a-zA-Z0-9]*\s*\n?", "", text)
        text = re.sub(r"\n?```\s*$", "", text)

        m = re.search(r'^(?:["\']use client["\'];?|import\s)', text, re.MULTILINE)
        if m and m.start() > 0:
            text = text[m.start():]

        return text.strip()